default_platform(:android)

platform :android do
  lane :deploy_to_play_store do
    # Customize this lane for deploying to the Play Store
    # You might want to use gradle to upload the APK to Play Store
    gradle(
      task: 'bundleRelease',
      build_type: 'Release',
      properties: {
        'android.injected.signing.store.file' => '/home/growlt189/fluttertest-keystore.jks',
        'android.injected.signing.store.password' => '1234',
        'android.injected.signing.key.alias' => 'growexx',
        'android.injected.signing.key.password' => '1234'
      }
    )

   
end
